### PR TITLE
Fix BC break from upgrade to PSR-15

### LINKED ISSUE #6: 1.1.0 seems to be broken
Please see these tests:
https://travis-ci.org/zendframework/zend-stratigility/jobs/332049603#L644

So the problem is only on the latest release. It's because the interface extends PSR-15 interface and method defined in the PSR-15 interface typehint against PST-15 interface, not as before interop interface. Basically 1.1.0 has a BC Break...

Refs http-interop/http-server-handler#12 by @webimpress

### PR DESCRIPTION
**Pull request by shadowhand**
Fixes #6

### CODE REVIEW

**Comment by oscarotero** [comment]
Not sure if it's worth having a 2.0 version with a breaking change instead just decrecate this package and telling to change to psr/http-server-middleware.

**Comment by michalbundyra** [comment]
@shadowhand what would be the point for devs upgrade to 2.0 not to PSR-15 straight away?
I think we should find another resolution to fix BC break introduced in 1.1.0 and have it fixed with 1.1.1 somehow...

**Comment by tuupola** [comment]
I also tend to think deprecating is enough. However, whatever is done should at least revert 1.1 and release 1.2 of `http-interop/http-server-middleware` which is does not break BC.

**Comment by shadowhand** [comment]
PR updated. The problem is that I failed to change the version requirement for `http-server-handler`, which was causing version `1.0.x` to be installed which did not extend the PSR interface.

**Comment by shadowhand** [comment]
This can be verified by looking at the [composer log of the failed PR](https://travis-ci.org/zendframework/zend-stratigility/jobs/332049603#L579-L587) where it did not update `http-interop/http-server-handler` to version `1.1`. If we merge this and tag it as `1.1.1` (or force a re-tag of `1.1.0`) the problem should be solved.

**Comment by michalbundyra** [comment]
@shadowhand 
I've tried to check it, here is my `composer.json`:
```json
{
    "require": {
        "http-interop/http-server-middleware": "dev-fix-bc-break"
    }
}
```
and when I run `composer update`, I've got:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - http-interop/http-server-middleware dev-fix-bc-break requires http-interop/http-server-handler ^1.1 -> satisfiable by http-interop/http-server-handler[1.1.0].
    - http-interop/http-server-handler 1.1.0 conflicts with http-interop/http-server-middleware[dev-fix-bc-break].
    - Installation request for http-interop/http-server-middleware dev-fix-bc-break -> satisfiable by http-interop/http-server-middleware[dev-fix-bc-break].
```

Any ideas?

**Comment by michalbundyra** [comment]
But anyway, I think it's not going to be a proper resolution. The problem is because `process` method  in this repo now typehints with Psr interface, not as before interop, so this change is not going to fix it !

**Comment by shadowhand** [comment]
@webimpress I am getting the same when I try it on a local copy, but not sure why it registers as a conflict.

To your point about the process method, it shouldn't matter because the Interop handler extends the Psr handler, therefore typing resolves correctly. The problem is only when handler `<1.1` is used.

**Comment by michalbundyra** [comment]
@shadowhand Hm... not sure, check this out:
https://3v4l.org/cP326

```php
interface PsrHandler {}
interface InteropHandler extends PsrHandler {}

interface Psr {
    public function process(PsrHandler $a);
}

interface Interop extends Psr {}

class Middleware implements Interop {
    public function process(InteropHandler $a) {
    }
}
```

and we have got:

```
Fatal error: Declaration of Middleware::process(InteropHandler $a) must be compatible with Psr::process(PsrHandler $a) in /in/cP326 on line 12
```

**Pull request closed without merging**
